name: "Bug Report"
description: "File a bug report"
title: "[ version of genshin ] [version of gimi] [version of raidenboss fix] error
  detail"
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
 - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version of the [FixRaidenBoss2 fix](https://github.com/Alex-Au1/Fix-Raiden-Boss/releases)
          required: true
        - label: I have searched [issues on Github](https://github.com/nhok0169/Fix-Raiden-Boss/issues) including closed ones and [issues on the mod site](https://gamebanana.com/tuts/15633) for similar issues. DO NOT post duplicates.
          required: true
        - label: I included the entire log [(as a screenshot or text)](https://gist.github.com/NawalJAhmed/2168f7659c08b6a033e7f6daf8db69a6) of my run of the fix
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description that is worded well enough to be understood
      placeholder: Provide any additional information, any suggested solutions, and as much context and examples as possible
    validations:
      required: true
